name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/tpc3/workadventure-admin:latest
      - name: Build only
        if: ${{ github.ref != 'refs/heads/main' }}
        id: docker_build_only
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: false
          tags: ghcr.io/tpc3/workadventure-admin:latest
